app_forum/urls.py
from django.urls import path

from . import views

app_name = "forum"


urlpatterns = [
    path("", views.TopicsListView.as_view(), name="index"),
    path("tag/<slug:slug>/", views.TagView.as_view(), name="tag"),
    path("search/", views.TopicSearchView.as_view(), name="search_topic"),
    path("manage-users/", views.UsersListView.as_view(), name="manage_users"),
    path(
        "manage-users/search/",
        views.UserSearchView.as_view(),
        name="search_users",
    ),
    path(
        "manage-users/change-group/<int:user_id>/<str:group>/",
        views.handle_change_group,
        name="change_group",
    ),
    path(
        "<int:topic_id>/delete/",
        views.TopicDeleteView.as_view(),
        name="delete_topic",
    ),
    path(
        "<int:topic_id>/update/",
        views.TopicUpdateView.as_view(),
        name="update_topic",
    ),
    path("add/", views.TopicCreateView.as_view(), name="create_topic"),
    path(
        "<int:topic_id>/posts/",
        views.PostsListView.as_view(),
        name="topic_posts",
    ),
    path(
        "<int:topic_id>/posts/search/",
        views.PostSearchView.as_view(),
        name="search_posts",
    ),
    path(
        "<int:topic_id>/posts/<int:post_id>/delete/",
        views.PostDeleteView.as_view(),
        name="delete_post",
    ),
    path(
        "<int:topic_id>/posts/<int:post_id>/update/",
        views.PostUpdateView.as_view(),
        name="update_post",
    ),
    path(
        "<int:topic_id>/posts/add/",
        views.PostCreateView.as_view(),
        name="create_post",
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('app_forum.urls')),
    path('authentication/', include('app_authentication.urls'))
]

app_forum/models/post.py
from typing import Any

from django.contrib.auth import get_user_model
from django.db import models

from .topic import Topic

User = get_user_model()


class Post(models.Model):
    date: Any = models.DateTimeField(auto_now_add=True, null=True)
    text: Any = models.TextField(max_length=1000)
    topic: Any = models.ForeignKey(
        Topic, on_delete=models.CASCADE, related_name="posts"
    )
    author: Any = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="+",
    )

    def __str__(self):
        return f"{self.pk}"

app_forum/models/topic.py
from typing import Any

from django.contrib.auth import get_user_model
from django.db import models
from taggit.managers import TaggableManager

User = get_user_model()


class Topic(models.Model):
    title: Any = models.TextField(max_length=1312)
    date: Any = models.DateTimeField(auto_now_add=True, null=True)
    author: Any = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
        related_name="+",
    )
    tag: Any = TaggableManager()

    def __str__(self):
        return f"{self.title}"

app_forum/forms.py
from django import forms

from .models import Post
from .models import Topic


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text"]


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = "__all__"

app_forum/views/manage_users.py
from typing import Any

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic

User = get_user_model()
url_login = reverse_lazy("auth:login")


def handle_change_group(
    request: HttpRequest, user_id: int, group: str
) -> HttpResponse:
    user = User.objects.get(id=user_id)
    group: Group = Group.objects.get(name=group)
    user.groups.clear()
    user.groups.add(group)
    return redirect("forum:manage_users")


class UsersListView(generic.ListView):
    model = User
    template_name = "app_forum/manage_users/manage_users.html"

    def get_queryset(self) -> Any:
        qs = super().get_queryset()
        search = self.request.session.get("search")
        if search:
            return qs.filter(username__icontains=search)
        return qs


class UserSearchView(generic.FormView):
    form_class = forms.Form
    success_url = reverse_lazy("forum:manage_users")
    http_method_names = ["post"]

    def form_valid(self, form: forms.Form) -> HttpResponse:
        search = self.request.POST["search"]
        self.request.session["search"] = search
        return super().form_valid(form)

app_forum/views/posts.py
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic

from app_forum.logic_forum import get_reverse_url
from app_forum.models import Post
from app_forum.models import Topic

url_login = reverse_lazy("auth:login")


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = url_login
    model = Post
    fields = ["text"]
    success_url = reverse_lazy("forum:index")
    template_name = "app_forum/posts/create_post.html"

    def form_valid(self, form: forms.ModelForm) -> HttpResponse:
        topic = self.kwargs["topic_id"]
        form.instance.author = self.request.user
        self.success_url = get_reverse_url(topic)
        form.instance.topic = Topic.objects.get(id=topic)
        rs = super().form_valid(form)
        return rs


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    login_url = url_login
    model = Post
    success_url = reverse_lazy("forum:index")
    template_name = "app_forum/posts/delete_post.html"
    pk_url_kwarg = "post_id"

    def form_valid(self, form: forms.ModelForm) -> HttpResponse:
        topic = self.kwargs["topic_id"]
        self.success_url = get_reverse_url(topic)
        rs = super().form_valid(form)
        return rs


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = url_login
    model = Post
    fields = ["text"]
    success_url = reverse_lazy("forum:index")
    template_name = "app_forum/posts/update_post.html"
    pk_url_kwarg = "post_id"

    def form_valid(self, form: forms.ModelForm) -> HttpResponse:
        topic = self.kwargs["topic_id"]
        self.success_url = get_reverse_url(topic)
        rs = super().form_valid(form)
        return rs

app_forum/views/tags.py
from django.http import HttpRequest
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views import generic
from taggit.models import Tag

from app_forum.models import Topic


class TagView(generic.View):
    def get(self, request: HttpRequest, slug, *args, **kwargs):
        tag = get_object_or_404(Tag, slug=slug)
        topics = Topic.objects.filter(tag=tag)
        common_tags = Topic.tag.most_common()
        return render(
            request,
            "app_forum/tags/tag.html",
            context={
                "title": f"#{tag}",
                "topics": topics,
                "common_tags": common_tags,
            },
        )

app_forum/views/topic.py
from typing import Any

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic

from app_forum.forms import TopicForm
from app_forum.models import Topic

User = get_user_model()
url_login = reverse_lazy("auth:login")


class TopicsListView(generic.ListView):
    paginate_by = 6
    model = Topic
    template_name = "app_forum/index.html"
    extra_context = {"form": TopicForm()}

    def get_queryset(self) -> Any:
        qs = super().get_queryset()
        search = self.request.session.get("search")
        if search:
            return qs.filter(title__icontains=search)
        return qs


class TopicSearchView(generic.FormView):
    form_class = forms.Form
    success_url = reverse_lazy("forum:index")
    http_method_names = ["post"]

    def form_valid(self, form: forms.Form) -> HttpResponse:
        search = self.request.POST["search"]
        self.request.session["search"] = search
        return super().form_valid(form)


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = url_login
    model = Topic
    fields = ["title", "tag"]
    success_url = reverse_lazy("forum:index")
    template_name = "app_forum/topics/create_topic.html"

    def form_valid(self, form: forms.ModelForm) -> HttpResponse:
        form.instance.author = self.request.user
        rs = super().form_valid(form)
        return rs


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    login_url = url_login
    model = Topic
    success_url = reverse_lazy("forum:index")
    template_name = "app_forum/topics/delete_topic.html"
    pk_url_kwarg = "topic_id"


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = url_login
    model = Topic
    fields = ["title", "tag"]
    success_url = reverse_lazy("forum:index")
    template_name = "app_forum/topics/update_topic.html"
    pk_url_kwarg = "topic_id"

app_forum/views/topic_posts.py
from typing import Any

from django import forms
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic

from app_forum.forms import PostForm
from app_forum.logic_forum import get_reverse_url
from app_forum.models import Post

User = get_user_model()


class PostsListView(generic.ListView):
    paginate_by = 6
    model = Post
    template_name = "app_forum/topics/topic_posts.html"
    extra_context = {"form": PostForm()}

    def get_queryset(self) -> Any:
        qs = super().get_queryset()
        search = self.request.session.get("search")
        if search:
            return qs.filter(
                topic=self.kwargs["topic_id"], text__icontains=search
            )
        return qs.filter(topic=self.kwargs["topic_id"])


class PostSearchView(generic.FormView):
    form_class = forms.Form
    success_url = reverse_lazy("forum:index")
    http_method_names = ["post"]

    def form_valid(self, form: forms.Form) -> HttpResponse:
        topic = self.kwargs["topic_id"]
        self.success_url = get_reverse_url(topic)
        search = self.request.POST["search"]
        self.request.session["search"] = search
        return super().form_valid(form)

app_forum/templates/app_forum/topics/create_topic.html
{% extends "app_forum/base.html" %}

{% block title %}Create topic{% endblock title %}

{% block content %}
{% include 'includes/navbar.html' %}

<div class="container" align="center">
    <form method="post">
        {% csrf_token %}
        {% for field in form %}

            <div class="mb-3">
                {{ field.label_tag }}
                {{ field.errors }}
                {{ field }}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>


</div>
{% endblock content %}

app_forum/templates/app_forum/topics/delete_topic.html
{% extends 'app_forum/base.html' %}
 
{% block content %}
<div class="container">
    {% include 'includes/navbar.html' %}

    <h1>Delete topic</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete topic and posts?</p>
        <br>
      <input type="submit" value="Confirm" />
    </form>

    <br>
</div>
{% endblock content %}

app_forum/templates/app_forum/topics/topic_posts.html
{% extends 'app_forum/base.html' %}
{% load filter_group %}

{% block title %} List posts {% endblock title %}

{% block content %}
{% include 'includes/navbar.html' %}
    {% if user.is_authenticated %}
    <div>
        <form action="add/" method="get">
            <p>
            <button class="btn btn-outline-primary" type="submit" value="Save">  Add post</button>
            </p>
        </form>
    </div>
    {% endif %}
<main role="main" class="container">
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h1 class="border-bottom border-gray pb-2 mb-0">Topic posts:</h1>
          {% for post in page_obj %}
        <div class="media text-muted pt-3" >
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              author: {{ post.author.username }}
            <strong class="d-block text-gray-dark">{{ post.text }} </strong>
              <div class="d-flex justify-content-between align-items-center">
                {% if user.pk == post.author.pk or user|has_group:"moderator" %}
                <div class="btn-group">
                  <a href="{% url 'forum:delete_post' post.topic.pk post.pk %}" class="btn btn-sm btn-outline-primary">DELETE</a>
                  <a href="{% url 'forum:update_post' post.topic.pk post.pk %}" class="btn btn-sm btn-outline-primary">UPDATE</a>
                </div>
                {% endif %}
                <small class="text-muted">{{ post.date }}</small>
              </div>
                <hr>
          </p>
        </div>
          {% endfor %}
      </div>
</main>
{% endblock content %}

{% block pagination %}
{% include 'includes/pagination.html' %}
{% endblock pagination %}

app_forum/templates/app_forum/topics/update_topic.html
{% extends 'app_forum/base.html' %}

{% block title %}Update topic{% endblock title %}

{% block content %}
{% include 'includes/navbar.html' %}



<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>


{% endblock content %}